### ISSUE TITLE
What is WebClient? How to use WebClient in SpringBoot application?

### ISSUE THREAD

**Issue by nilandev** [StackTipsLab/content#14]

**Comment by nilandev** [comment]
Live on
https://stacktips.com/articles/what-is-webclient-how-to-use-webclient-in-java-springboot

**Comment by kiranraoboinapally** [comment]
https://github.com/kiranraoboinapally/java-practice-problems/tree/main/java/OOPS check this repository  for OOPS Cncepts programs and check one more for concepts https://github.com/kiranraoboinapally/java-practice-problems/blob/main/java/concepts_md/oops.md
